### ISSUE TITLE
having issues

### ISSUE THREAD

**Issue by XahidEx** [G3root/nafeez.xyz#1]
![Screenshot_20220524-234557_Firefox](https://user-images.githubusercontent.com/88249321/170099489-d31030e4-47b0-4707-a144-346327566cc4.png)
Json fetching issue. 😪

**Comment by G3root** [comment]
thanks for the reporting i'll check that today ❤️

**Comment by G3root** [comment]
i have hard-coded the api responses until i get a api key for opensea 😞 .
